{% set version = "0.16.0" %}

package:
  name: py-serializable
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/py-serializable/py-serializable-{{ version }}.tar.gz
    sha256: 80d3401ede78ab350d66ef8c167a688790a1ca8e11b563e8e68283bf29f34a01
  - folder: src
    url: https://github.com/madpah/serializable/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 51de27b5c63d95a2b3058cebc763c773512c4211453fb89dd832db4e2d0042e5

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - defusedxml >=0.7.1,<0.8.0
    - python >=3.7

test:
  source_files:
    - src/tests
  imports:
    - serializable
  commands:
    - pip check
    - cd src && pytest -vv --cov=serializable --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=82 -k "not (serializable_with_defaultNS or serializable_no_defaultNS) "
    - mypy -p serializable
  requires:
    - lxml
    - mypy
    - pip
    - pytest-cov
    - xmldiff

about:
  home: https://github.com/madpah/serializable
  summary: Library for serializing and deserializing Python Objects to and from JSON and XML.
  license: Apache-2.0
  license_file: dist/LICENSE
  doc_url: https://py-serializable.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
